
export const FETCH_ISSUE_LIST =
'GITHUB/FETCH_ISSUE_DETAILS';
export const FETCH_ISSUE_LIST_SUCCESS =
'GITHUB/FETCH_ISSUE_LIST_SUCCESS';
export const FETCH_ISSUE_LIST_ERROR =
'GITHUB/FETCH_ISSUE_LIST_ERROR';
export const FETCH_ISSUE_LIST_KEY = 'gitData';

export const FETCH_ISSUE_DETAILS =
'GITHUB/FETCH_ISSUE_DETAILS';
export const FETCH_ISSUE_DETAILS_SUCCESS =
'GITHUB/FETCH_ISSUE_DETAILS_SUCCESS';
export const FETCH_ISSUE_DETAILS_ERROR =
'GITHUB/FETCH_ISSUE_DETAILS_ERROR';
export const FETCH_ISSUE_DETAILS_KEY = 'gitDetail';

export const FETCH_COMMENT_DETAILS =
'GITHUB/FETCH_COMMENT_DETAILS';
export const FETCH_COMMENT_DETAILS_SUCCESS =
'GITHUB/FETCH_COMMENT_DETAILS_SUCCESS';
export const FETCH_COMMENT_DETAILS_ERROR =
'GITHUB/FETCH_COMMENT_DETAILS_ERROR';
export const FETCH_COMMENT_DETAILS_KEY = 'gitComment';

export const FETCH_ISSUE_STATE =
'GITHUB/FETCH_ISSUE_STATE';
export const FETCH_ISSUE_STATE_SUCCESS =
'GITHUB/FETCH_ISSUE_STATE_SUCCESS';
export const FETCH_ISSUE_STATE_ERROR =
'GITHUB/FETCH_ISSUE_STATE_ERROR';
export const FETCH_ISSUE_STATE_KEY = 'gitState';
