
export const FETCH_ISSUE_LIST =
'GITHUB/FETCH_ISSUE_LIST';
export const FETCH_ISSUE_LIST_SUCCESS =
'GITHUB/FETCH_ISSUE_LIST_SUCCESS';
export const FETCH_ISSUE_LIST_ERROR =
'GITHUB/FETCH_ISSUE_LIST_ERROR';
export const FETCH_ISSUE_LIST_KEY = 'gitData';
