
export const FETCH_ISSUE_DETAILS =
'GITHUB/FETCH_ISSUE_DETAILS';
export const FETCH_ISSUE_DETAILS_SUCCESS =
'GITHUB/FETCH_ISSUE_DETAILS_SUCCESS';
export const FETCH_ISSUE_DETAILS_ERROR =
'GITHUB/FETCH_ISSUE_DETAILS_ERROR';
export const FETCH_ISSUE_DETAILS_KEY = 'gitData';

export const FETCH_COMMENT_DETAILS =
'GITHUB/FETCH_COMMENT_DETAILS';
export const FETCH_COMMENT_DETAILS_SUCCESS =
'GITHUB/FETCH_COMMENT_DETAILS_SUCCESS';
export const FETCH_COMMENT_DETAILS_ERROR =
'GITHUB/FETCH_COMMENT_DETAILS_ERROR';
export const FETCH_COMMENT_DETAILS_KEY = 'gitComment';
